### ISSUE TITLE
Demo Checklist

### ISSUE THREAD

**Issue by seliopou** [frenetic-lang/frenetic#206]
## Rock-solid Infrastructure
- [x] Execute the shift to Jane Street core/async
- [ ] Establish release process for projects
- [ ] Release "1.0" ocaml-openflow library
- [ ] Release "1.0" Frenetic compiler implementation
## Resurrect Features
- [ ] Queries and PacketOut channels
- [ ] Wildcard patterns (essential for layer 3 routing)
- [ ] Consistent updates
## Other Language Bindings
- [ ] Java bindings to expose NetKAT, compiler, runtime
- [ ] Pick additional "scripting language to do the same"
## Applications
- [x] Pick 2-3 demos to run that showcase the language's strengths
- [x] Cook up slick visualization (D3?)
